msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2024-08-18 09:06+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI +ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0\n"
"Language-Code: en\n"
"Language-Name: English\n"
"Preferred-Encodings: utf-8 latin1\n"
"Domain: DOMAIN\n"

#: ../validators/IdValidator.py:26
msgid "Id $id is already in use"
msgstr "Идентификатор $id уже используется"

#: ../validators/IdValidator.py:17
msgid "Spaces are not allowed in ids"
msgstr "В идентификаторе нельзя использовать пробелы."

#: ../validators/RegexValidator.py:46
msgid "Validation failed($name): $value of type $type, expected 'string'"
msgstr "Проверка ($name) не пройдена: $value типа $type, должна быть 'строковой'"

#: ../validators/RegexValidator.py:65
msgid "Validation failed($name): '$value' $errmsg"
msgstr "Проверка ($name) не пройдена: '$value' $errmsg"

#: ../validators/EmptyValidator.py:45
msgid "Validation failed($name): '$value' is not empty."
msgstr "Проверка ($name) не пройдена: '$value' не пустое."

#: ../validators/RangeValidator.py:41
msgid "Validation failed($name): '$value' out of range($min, $max)"
msgstr "Проверка ($name) не пройдена: '$value' не в допуске($min, $max)"

#: ../validators/SupplValidators.py:103
msgid "Validation failed($name): could not convert $value to a date."
msgstr "Проверка ($name) не пройдена: $value не сконвертировать в дату."

#: ../validators/RangeValidator.py:33
msgid "Validation failed($name): could not convert '$value' to number"
msgstr "Проверка ($name) не пройдена: $value не сконвертировать в число."

#: ../validators/SupplValidators.py:94
msgid "Validation failed($name): value is empty ($value)."
msgstr "Проверка ($name) не пройдена: значение $value пусто."

#: ../validators/SupplValidators.py:71
msgid "Validation failed($name: Uploaded data is too large: ${size}MB (max ${max}MB)"
msgstr "Проверка не пройдена($name: Объем загруженных данных слишком велик: ${size}MB (max ${max}MB)"

#: ../validators/BaseValidators.py:51
msgid "contains unprintable characters"
msgstr "содержит символы, которые не печатаются"

#: ../validators/BaseValidators.py:37
msgid "is not a decimal number."
msgstr "не десятичное число"

#: ../validators/BaseValidators.py:95
msgid "is not a valid email address."
msgstr "не верный адрес электронной почты."

#: ../validators/BaseValidators.py:74
msgid "is not a valid international phone number."
msgstr "не верный формат международного телефонного номера."

#: ../validators/BaseValidators.py:88
msgid "is not a valid url."
msgstr "не верный адрес (url)."

#: ../validators/BaseValidators.py:66
msgid "is not a valid us phone number."
msgstr "не верный формат телефонного номера."

#: ../validators/BaseValidators.py:81
msgid "is not a valid zip code."
msgstr "не верный формат индекса."

#: ../validators/BaseValidators.py:58
msgid "is not a well formed SSN."
msgstr "не верный SSN."

#: ../validators/BaseValidators.py:44
msgid "is not an integer."
msgstr "не целое число."

#: ../validators/BaseValidators.py:109
msgid "this name is not a valid identifier"
msgstr "это название не подходит, как идетнификатор"

#: ../validators/ExpressionValidator.py:94
msgid "validation failed, expr was:$expr"
msgstr "Проверка не прошла: $expr"
